name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Grant execute permission to gradlew
      run: |
        icacls .\gradlew /grant Everyone:F
        # Hoặc nếu muốn thay thế bằng chmod thì sẽ cần một môi trường bash.
        # chmod +x ./gradlew

    - name: Build with Gradle
      run: .\gradlew build
